//! Smoke test: run `demo::generate_assets()` against a clean state and
//! verify every advertised demo character produces a frame_001.png with
//! the expected dimensions. This is the closest we can get to "I ran the
//! app and saw five characters appear" without spinning up a display.
//!
//! Both checks live in one test so cargo's parallel runner doesn't race
//! two `set_current_dir` calls against each other.
//!
//! `generate_assets()` writes to the *relative* path `assets/demo/...`, so
//! it lands wherever the process cwd points. This test used to point that
//! at `CARGO_MANIFEST_DIR` and `remove_dir_all` the real `assets/demo`
//! before regenerating it — meaning a plain `cargo test` deleted 34
//! committed files and rewrote them in place. The regenerated bytes were
//! not identical to the committed ones either, so the working tree came
//! back dirty and the diff was invisible in review (binary, one pixel).
//! Worse, a generator that panicked midway would leave the developer's
//! checkout with the shipped assets destroyed.
//!
//! Everything therefore happens inside a scratch directory now. Nothing
//! here may touch the repository.

use std::path::{Path, PathBuf};

const DEMO_DIRS: &[(&str, &str)] = &[
    ("assets/demo/ghost", "frame_001.png"),
    ("assets/demo/slime", "frame_001.png"),
    ("assets/demo/heart", "frame_001.png"),
    ("assets/demo/star", "frame_001.png"),
    ("assets/demo/cat", "frame_001.png"),
];

/// Sentinel size that all demo characters target. If a generator silently
/// drops to a smaller size the test catches it.
const EXPECTED_PX: u32 = 128;

/// A private directory to generate into, named after this process so
/// concurrent runs can't collide. Removed on the way out.
struct Sandbox(PathBuf);

impl Sandbox {
    fn new() -> Self {
        let dir = std::env::temp_dir().join(format!("anima-demo-gen-{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&dir);
        std::fs::create_dir_all(&dir).expect("create sandbox");
        std::env::set_current_dir(&dir).expect("enter sandbox");
        Self(dir)
    }
}

impl Drop for Sandbox {
    fn drop(&mut self) {
        // Leave cwd somewhere that still exists before deleting the
        // sandbox, or a later `std::fs` call in this process resolves
        // relative paths against a removed directory.
        let _ = std::env::set_current_dir(std::env::temp_dir());
        let _ = std::fs::remove_dir_all(&self.0);
    }
}

#[test]
fn generate_assets_full_smoke() {
    let repo = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    let sandbox = Sandbox::new();

    // ── Step 1: clean state → generate → expect five characters at 128 px.
    anima_engine::demo::generate_assets();

    for (dir, first_frame) in DEMO_DIRS {
        let frame_path = sandbox.0.join(dir).join(first_frame);
        assert!(
            frame_path.exists(),
            "missing first frame for demo char: {}",
            frame_path.display()
        );
        let (w, h) = image::image_dimensions(&frame_path)
            .unwrap_or_else(|e| panic!("can't read dims of {}: {e}", frame_path.display()));
        assert_eq!(w, EXPECTED_PX, "{}: width", dir);
        assert_eq!(h, EXPECTED_PX, "{}: height", dir);
    }

    // ── Step 2: idempotency. A second call must not rewrite anything.
    let baseline: Vec<_> = DEMO_DIRS
        .iter()
        .map(|(dir, frame)| {
            std::fs::metadata(Path::new(dir).join(frame))
                .unwrap()
                .modified()
                .unwrap()
        })
        .collect();

    // Filesystem mtime resolution can be 1 s — sleep enough to guarantee
    // a rewrite would land on a fresh second.
    std::thread::sleep(std::time::Duration::from_millis(1200));

    anima_engine::demo::generate_assets();
    for ((dir, frame), prev) in DEMO_DIRS.iter().zip(baseline) {
        let now = std::fs::metadata(Path::new(dir).join(frame))
            .unwrap()
            .modified()
            .unwrap();
        assert_eq!(
            prev, now,
            "demo at {dir} was rewritten on a no-op generate_assets() call"
        );
    }

    // ── Step 3: the repository must be untouched. This is the regression
    // guard for the behaviour described in the module docs.
    assert!(
        repo.join("assets/demo/star/frame_001.png").exists(),
        "the test generated into the repository instead of the sandbox"
    );
}
